<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD -->
<!DOCTYPE elearning [
    <!ELEMENT elearning (course+)>

    <!ELEMENT course (title, instructor, students)>
    <!ATTLIST course 
        id CDATA #REQUIRED 
        category CDATA #REQUIRED
    >

    <!ELEMENT title (#PCDATA)>

    <!ELEMENT instructor (name, email)>
    <!ATTLIST instructor id CDATA #REQUIRED>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>

    <!ELEMENT students (student+)>
    <!ELEMENT student (name)>
    <!ATTLIST student 
        id CDATA #REQUIRED 
        progress CDATA #REQUIRED
    >
]>

<!-- XML -->
<elearning>
    <course id="C001" category="Lập trình">
        <title>Python cơ bản</title>
        <instructor id="I001">
            <name>Nguyễn Văn A</name>
            <email>nguyenvana@gmail.com</email>
        </instructor>
        <students>
            <student id="S001" progress="80">
                <name>Trần Thị B</name>
            </student>
            <student id="S002" progress="50">
                <name>Hoàng Minh C</name>
            </student>
        </students>
    </course>

    <course id="C002" category="Thiết kế">
        <title>Thiết kế Web với Figma</title>
        <instructor id="I002">
            <name>Trần Thị D</name>
            <email>trand@gmail.com</email>
        </instructor>
        <students>
            <student id="S003" progress="90">
                <name>Nguyễn Văn E</name>
            </student>
            <student id="S004" progress="70">
                <name>Lê Thị F</name>
            </student>
        </students>
    </course>
</elearning>
