<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD -->
<!DOCTYPE thuvien [
    <!ELEMENT thuvien (sach+)>
    <!ELEMENT sach (title, author, year, genre)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
]>


<!-- XML -->
<thuvien>
    <sach>
        <title>Đắc Nhân Tâm</title>
        <author>Dale Carnegie</author>
        <year>1936</year>
        <genre>Kỹ năng sống</genre>
    </sach>
    <sach>
        <title>Lập Trình C++ Cơ Bản</title>
        <author>Nguyễn Văn A</author>
        <year>2020</year>
        <genre>Giáo trình</genre>
    </sach>
    <sach>
        <title>Harry Potter và Hòn đá Phù thủy</title>
        <author>J.K. Rowling</author>
        <year>1997</year>
        <genre>Tiểu thuyết</genre>
    </sach>
</thuvien>